# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a8cccf0151ed98f1bb02f6a7996278e88cff6b413853836f1b19c0d10fa1842901a0466bebba912e9da23febf9c2b971627f9dd35f723688802c88e2061e0f7

test:
  secret_key_base: 9ac7843e914be6a9c83b2e9530171cec22a44603fa8d981e060bce36e726f5fa638e54122db23565460a107826ee9c9229c208b25d5bb5173b309d566a410b7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
